# This is the config file for ledgerweb
#
# 1. flask
hostip: 0.0.0.0
hostport: 5000

# 2. rclone
remotename: Nextcloud
remotepath: /accounting/

# 3. ledger
currency: EUR
accounts:
- Assets:Checking
- Expenses:Food
- Income:Paycheck
favs:
    EDEKA:
        from: Assets:Checking
        to: Expenses:Food
    REWE:
        from: Assets:Checking
        to: Expenses:Food
    Alnatura:
        from: Assets:Checking
        to: Expenses:Food
